# Generated by Django 4.0.1 on 2022-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermodel',
            name='guild_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
